# ServerSelector config file
command: servers # Name of command, as typed by users
allowSubcommands: true # Allows user to select a server using /servers <serverid>
aliases: # Any aliases for the selector command
  - srv
compassServers:
  - Hub
useBungeePermissions: false # if true, bungeecord.command.server and bungeecord.server.x are used instead of perms defined below
permissionPrefix: serverselector # prefix of all permission nodes used by this plugin
permission: selector # permission node requred to open selector menu. do not include prefix
rows: 1 # number of chest rows to show in ui
title: "<color:red>Server Selector" # title or name of chest ui
servers:
  hub:
    slot: 0
    item: SPAWNER
    alias: h
    name: "<color:blue>Hub"
    permission: server.hub
  survival:
    slot: 1
    item: CRAFTING_TABLE
    alias: s
    name: "<color:blue>Survival"
padding:
  fill: true
  item: WHITE_STAINED_GLASS_PANE
messages:
  connect: <color:green>Connecting to <servername>...
  failure: <color:red>Could not connect to <servername>
