command: servers
aliases:
  - srv
useBungeePermissions: false
permission: serverselector.selector
title: "ยง9Server Selector"
servers:
  hub:
    slot: 0
    item: SPAWNER
    name: "ยง5Hub"
  survival:
    slot: 1
    item: CRAFTING_TABLE
    name: "ยง5Survival"
padding:
  fill: true
  item: BLACK_STAINED_GLASS_PANE
