# ServerSelector config file
command: servers # Name of command, as typed by users
aliases: # Any aliases for the selector command
  - srv
useBungeePermissions: false # if true, bungeecord.command.server and bungeecord.server.x are used instead of perms defined below
permissionPrefix: serverselector # prefix of all permission nodes used by this plugin
permission: selector # permission node requred to open selector menu. do not include prefix
rows: 1 # number of chest rows to show in ui
title: "ยง9Server Selector" # title or name of chest ui
servers:
  hub:
    slot: 0
    item: SPAWNER
    name: "ยง5Hub"
    permission: server.hub
  survival:
    slot: 1
    item: CRAFTING_TABLE
    name: "ยง5Survival"
padding:
  fill: true
  item: WHITE_STAINED_GLASS_PANE
messages:
  connect: Connecting to {SERVERNAME}...
  failure: Could not connect to {SERVERNAME}
